# Generated by Django 4.0.6 on 2022-07-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_remove_closedlisting_closed_listing_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='closedlisting',
            name='closed_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
